### ISSUE TITLE
front.py実行時のエラー

### ISSUE THREAD

**Issue by nobkono** [hamamoto-lab/imageViewer#11]
imageViewerレポジトリをクローンし、env.ymlでconda env createしました。
windows power shellからcd ../nobuji_kono/imageViewerし、conda activate imageViewerし、
python3 front.pyした後のエラーメッセージがでてしまいました↓

(imageViewer) nobuji_kono@DESKTOP-69AT7NJ:~/imageViewer$ python3 front.py
2023-07-05 11:29:22.216 WARNING streamlit.runtime.state.session_state_proxy: Session state does not function when running a script without `streamlit run`
Traceback (most recent call last):
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 378, in __getitem__
    return self._getitem(widget_id, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 423, in _getitem
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 119, in __getattr__
    return self[key]
           ~~~~^^^^^
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 90, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 113, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 380, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "samples". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nobuji_kono/imageViewer/front.py", line 250, in <module>
    main()
  File "/home/nobuji_kono/imageViewer/front.py", line 119, in main
    st.session_state.log = [0 for _ in range(len(st.session_state.samples))]
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nobuji_kono/miniforge3/envs/imageViewer/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "samples". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by t2ag3** [comment]
`data`ディレクトリにはファイルが正しく入っていますか？
何も入っていない状態で実行するとエラーがでます。
